#!/usr/bin/perl
use strict;
use warnings;
use Net::Twitter;

use Net::Twitter;

my $nt = Net::Twitter->new(
    traits => [qw/OAuth API::RESTv1_1/],
    map { $_ => $ENV{"$_"} || die "ENV $_ not set" }
      qw(
      consumer_secret
      consumer_key
      access_token
      access_token_secret
      )
);

my $result = $nt->update('Hello, world!');
